#!/bin/bash

# Setup crossplatform definitions

export USR_OPT=$HOME/opt


export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/bin:$PATH

[ -f "$HOME/.ghcup/env" ] && source "$HOME/.ghcup/env" # ghcup-env
