#!/bin/bash

pip3 install dotfiles --user

# setup dotfilesrc symlink
dotfilesrepopath=$(cd "$(dirname "$0")" && pwd)
ln -f -s $dotfilesrepopath/dotfilesrc $HOME/.dotfilesrc
perl -pi.bak -e "s:repository\s*=.*:repository = $dotfilesrepopath:" $dotfilesrepopath/dotfilesrc

# Check if we can move the current bashrc to local
if [ -f "$HOME/.bashrc-local" ]; then
	echo setup: cannot create file ‘$HOME/.bashrc-local’: File exists 1>&2
	exit 1
fi
if [ -f "$HOME/.bashrc" ]; then
	mv $HOME/.bashrc $HOME/.bashrc-local
fi
if [ -f "$HOME/.profile-local" ]; then
	echo setup: cannot create file ‘$HOME/.profile-local’: File exists 1>&2
	exit 1
fi
if [ -f "$HOME/.profile" ]; then
	mv $HOME/.profile $HOME/.profile-local
fi

pip3 show dotfiles -f | grep "Location:"
pip3 show dotfiles -f | grep "/bin/dotfiles$"

if [[ "$OSTYPE" == "darwin"* ]]; then
  $HOME/Library/Python/3.9/bin
else
  $HOME/.local/bin/dotfiles --sync
fi


