#!/bin/bash

pip install dotfiles --user

# setup dotfilesrc symlink
dotfilesrcpath=$(cd "$(dirname "$0")" && pwd)
ln -f -s $dotfilesrcpath/dotfilesrc $HOME/.dotfilesrc

$HOME/.local/bin/dotfiles --sync

